### ISSUE TITLE
Capturing values in thread first or thread last statements

### ISSUE THREAD

**Issue by jefffriesen** [vvvvalvalval/scope-capture#32] opened 2018-10-08 15:42 UTC
It would be nice to be able to capture each step in threading macros. For example:

```clj
(defn abbr-into-set
  [permit keyword-map]
  (sc/spy
   (into #{} (->> keyword-map
                  (filter #(include-exclude-match? permit %))
                  (map first)
                  (map name)))))
```

I could capture the intermediate state for each step in this thread last macro. When I tried this spy only captured the function arguments. I couldn't see a way to capture the rest in the documentation. Do you think this would be a good feature?

**Comment by vvvvalvalval** [comment] 2018-10-08 15:52
@jefffriesen This use case seems too specific for scope-capture - it's more of a job for a tracing library or a custom macro.

Note that, if each step is a pure and deterministic computation (as it should be most of the time, since Clojure encourages functional programming!), you can get the desired result by reproducing the context of the expression + some paredit-fu to re-evaluate a growing number of steps (e.g: move the closing paren of the `(->> ...)` expression to right after `keyword-map`, evaluate, then slurp in the next expression, evaluate, and so on.)
 
You could also imagine creating your own `spy->>` macro that logs and/or records and/or spies each intermediate step!

**Closed by vvvvalvalval** 2018-10-08 15:52 UTC

**Comment by jefffriesen** [comment] 2018-10-08 15:56
Ok, thanks @vvvvalvalval
